services:
    php:
        build: ./config/php
        container_name: 'lema-php'
        expose:
            - 9000
        depends_on:
            - mariadb
        volumes:
            - '../:/var/www/html:z'
            - ./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

    nginx:
        build: ./config/nginx
        container_name: lema-nginx
        environment:
            PROXY_READ_TIMEOUT: '120s'
        ports:
            - 80:80
        links:
            - 'php'
        volumes:
            - '../:/var/www/html:z'

    mariadb:
        image: mariadb:latest
        container_name: lema-mariadb
        restart: 'on-failure'
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
        volumes:
            - ./DBDATA:/var/lib/mysql

    adminer:
        image: adminer:latest
        restart: on-failure
        environment:
            ADMINER_DESIGN: pepa-linha
        ports:
            - 8080:8080
        volumes:
            - ./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini