version: '3.9'
services:
  db:
    image: postgres:latest
    restart: 'on-failure'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: example_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    build: ./adminer/
    restart: 'on-failure'
    ports:
      - 8080:8080